table 'Param Distância'
	lineageTag: 06129a5e-d128-4c07-b267-9237065ec7bb

	measure 'Param Distância Valor' = SELECTEDVALUE('Param Distância'[Param Distância], 500)
		formatString: #,0
		lineageTag: 3e30e840-86dd-4b39-b55c-c30a04194565

	column 'Param Distância'
		dataType: double
		formatString: #,0
		lineageTag: 7918e90d-e82c-455f-95c2-606439b440a0
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'Param Distância' = calculated
		mode: import
		source = GENERATESERIES(0, 4000, 50)

	annotation PBI_Id = ParamDistancia

