table 'Param Peso'
	lineageTag: 5024cd0f-fc62-4269-a884-c1f014eab29d

	measure 'Param Peso Valor' = SELECTEDVALUE('Param Peso'[Param Peso], 2000)
		formatString: #,0
		lineageTag: 0cf517c1-80d0-42a5-8079-d2180ae06088

	column 'Param Peso'
		dataType: int64
		formatString: #,0
		lineageTag: e269bf97-78aa-486f-95d5-f85261672eed
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'Param Peso' = calculated
		mode: import
		source = GENERATESERIES(0, 30000, 250)

	annotation PBI_Id = ParamPeso

