table 'Param Prazo'
	lineageTag: f4cecc79-b76b-45fa-964e-f984f0c418ae

	measure 'Param Prazo Valor' = SELECTEDVALUE('Param Prazo'[Param Prazo], 12)
		formatString: 0
		lineageTag: 09d25b34-8413-4330-8259-0e535a645778

	column 'Param Prazo'
		dataType: int64
		formatString: 0
		lineageTag: 0c699f38-28c0-4fbf-bdaf-ee198086b726
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'Param Prazo' = calculated
		mode: import
		source = GENERATESERIES(1, 60, 1)

	annotation PBI_Id = ParamPrazo

