table 'Param Frete'
	lineageTag: 01fd1861-5c38-44d7-8874-dfcba2002965

	measure 'Param Frete Valor' = SELECTEDVALUE('Param Frete'[Param Frete], 20)
		formatString: \R$ #,0
		lineageTag: b098e2d0-9703-4f31-946b-7f6be7b6bf41

	column 'Param Frete'
		dataType: double
		formatString: \R$ #,0
		lineageTag: 1be9cd71-6749-4357-a45f-d2bd96e1595e
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition 'Param Frete' = calculated
		mode: import
		source = GENERATESERIES(0, 400, 5)

	annotation PBI_Id = ParamFrete

